"""Telegram user model."""
from sqlalchemy import BigInteger, String, false
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base, TimestampMixin
from app.roles import Role, RoleType


class User(Base, TimestampMixin):
    __tablename__ = "users"

    # telegram_id is the user's id from Telegram. It can be large, hence BigInteger,
    # and it is unique and present in every update, so we use it as the primary key.
    # autoincrement=False: the id is assigned by Telegram, never generated by us.
    telegram_id: Mapped[int] = mapped_column(
        BigInteger, primary_key=True, autoincrement=False
    )

    username: Mapped[str | None] = mapped_column(String(32))
    first_name: Mapped[str | None] = mapped_column(String(64))
    # Raw language_code as reported by Telegram (kept for reference/history).
    language_code: Mapped[str | None] = mapped_column(String(8))
    # Our normalized UI locale (one of i18n.SUPPORTED_LOCALES). Drives
    # localization; derived from language_code at registration, defaults to "en".
    locale: Mapped[str] = mapped_column(String(8), default="en", server_default="en")

    # Checked in middleware: banned users never reach the handlers.
    is_banned: Mapped[bool] = mapped_column(default=False, server_default=false())

    # Role bitmask (see app/roles.py). Stored as a plain integer; 0 = default user.
    role: Mapped[Role] = mapped_column(RoleType, default=Role.USER, server_default="0")

    def __repr__(self) -> str:
        return f"<User telegram_id={self.telegram_id} username={self.username!r}>"
