"""issued_tickets

Revision ID: 17a197fc3157
Revises: ff067b02d0f1
Create Date: 2026-06-15 15:13:18.725476
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '17a197fc3157'
down_revision: Union[str, None] = 'ff067b02d0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issued_tickets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(length=64), nullable=False),
    sa.Column('coordinator_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('sent_email', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coordinator_id'], ['users.telegram_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issued_tickets_coordinator_id'), 'issued_tickets', ['coordinator_id'], unique=False)
    op.create_index(op.f('ix_issued_tickets_created_at'), 'issued_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_issued_tickets_ticket_id'), 'issued_tickets', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issued_tickets_ticket_id'), table_name='issued_tickets')
    op.drop_index(op.f('ix_issued_tickets_created_at'), table_name='issued_tickets')
    op.drop_index(op.f('ix_issued_tickets_coordinator_id'), table_name='issued_tickets')
    op.drop_table('issued_tickets')
    # ### end Alembic commands ###
